### ISSUE TITLE
Instruction to run learn test incorrect

### ISSUE THREAD

**Issue by sopharsogood** [learn-co-curriculum/ruby-oo-inheritance-modules#2]
The instructions for Code-Along 2 end with:

"Note: Run the learn test command to pass all the local tests for this lab. We will be altering the methods where these tests will no longer be valid."

This is incorrect; the learn tests pass after, not before, Code-Along 3.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

Thanks for contributing to the Flatiron School curriculum! 💙
